### ISSUE TITLE
Changing screens

### ISSUE THREAD

**Issue by athens77** [Gallo-ICS2O1a/cpt-maria-sofia-stella-athena-yay#1]
We are trying to make it so on the start screen, if the mouse clicks inside the "Start" rectangle, it changes to the game screen

**Comment by MrGallo** [comment]
You need a global variable to remember what screen you are currently on. Like `screen = “menu”`. The draw function needs an if statement inside it. `if screen == “menu”:` and then `elif screen == “whatever else”':`

**Comment by MafiaParadox** [comment]
The problem was fixed. :)
