### ISSUE TITLE
Adding Score

### ISSUE THREAD

**Issue by athens77** [Gallo-ICS2O1a/cpt-maria-sofia-stella-athena-yay#2]
We are trying to add a score every time the ellipse passes an obstacle without colliding, but the score is added unevenly every time (ie. for the first obstacle: +2, second obstacle: +2, third obstacle: +1, fourth obstacle +1)

**Comment by MrGallo** [comment]
In the code, it looks like the check at line 161 happens more than once. If you have passed the obstacle, you should no longer check if you collide or if you have passed it.

https://github.com/Gallo-ICS2O1a/cpt-maria-sofia-stella-athena-yay/blob/ba1b1942503dfdf0bea766a2f1fd7a4554e952dd/Flappy%20Ellipse%20Sketch.py#L153-L162

**Comment by athens77** [comment]
Solved
