### ISSUE TITLE
Wrong indent level(?)

### ISSUE THREAD

**Issue by MrGallo** [Gallo-ICS2O1a/cpt-maria-sofia-stella-athena-yay#3]
It looks as though this if-block is not indented properly. It looks like it is supposed to be indented one more level to fall within the if-block just above it.
https://github.com/Gallo-ICS2O1a/cpt-maria-sofia-stella-athena-yay/blob/ba1b1942503dfdf0bea766a2f1fd7a4554e952dd/Flappy%20Ellipse%20Sketch.py#L224-L230

**Comment by athens77** [comment]
We indented the if statement to fall in line with the if block above it

**Comment by athens77** [comment]
Edit: We do not need to indent the if statements because the if block above it is part of the gamescreen, and collision and gameover screen do not work in the gamescreen block
